# This file was generated by GoReleaser. DO NOT EDIT.
cask "muga" do
  name "muga"
  desc "Muga CLI — observability for your services"
  homepage "https://muga.sh"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "muga"

  on_macos do
    on_intel do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_darwin_amd64.tar.gz"
      sha256 "b6c4d7c449a10ecdbd44124549b4be79f7bee92b2585a4ec0b39c9cb607077a4"
    end
    on_arm do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_darwin_arm64.tar.gz"
      sha256 "455dc5a17971ba8093acb343dabfe3e1dc8da3bdcdc60d3c128fc83b8d7e8f14"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_linux_amd64.tar.gz"
      sha256 "bfc42759559ee1acab1eb2a5523c08ff0618f0955e9075577bc9d5f0aed8ef00"
    end
    on_arm do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_linux_arm64.tar.gz"
      sha256 "68f8d52d55f9551ac396c1231701b1c947f9124faa0d55e0bbbb91c811f8a2d4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muga"]
    end
  end

  # No zap stanza required
end
