# This file was generated by the release workflow. DO NOT EDIT.
cask "muga" do
  name "muga"
  desc "Muga CLI — observability for your services"
  homepage "https://muga.sh"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "muga"

  on_macos do
    on_intel do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_darwin_amd64.tar.gz"
      sha256 "c335adae8a15b382244d5253036c6118e619a51975f587aa0fc8ae770b0deaad"
    end
    on_arm do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_darwin_arm64.tar.gz"
      sha256 "877d11d1acb56789ac2ea2a05cc2d24a9b039c0548074eedbe725a049d252f03"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_linux_amd64.tar.gz"
      sha256 "9e6c655699b9cf8e354f5380947ec81ed99474e435942b017ba41199d4dc9f62"
    end
    on_arm do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_linux_arm64.tar.gz"
      sha256 "c453bba2ba638c1ab04a2615ca39383e9bd2a2e13b7d6b19662cf2fe8faa3806"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muga"]
    end
  end

  # No zap stanza required
end
