# This file was generated by GoReleaser. DO NOT EDIT.
cask "muga" do
  name "muga"
  desc "Muga CLI — observability for your services"
  homepage "https://muga.sh"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "muga"

  on_macos do
    on_intel do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_darwin_amd64.tar.gz"
      sha256 "dd8f04ba0655e1a43f3f68c90a2e7ce879ae216a091948c9c4321480a2ce7117"
    end
    on_arm do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_darwin_arm64.tar.gz"
      sha256 "804b02860b574d08b35730f52ca2c688de531841556993c56576453903196f32"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_linux_amd64.tar.gz"
      sha256 "489fec1c9ae850b3b8d19b513b62860744ed14ce7d069f4334a9c3afe220a0ea"
    end
    on_arm do
      url "https://github.com/mugahq/muga/releases/download/v#{version}/muga_linux_arm64.tar.gz"
      sha256 "13fb9ee3ffe0e5be5a192a81f7f328cc21af62cc365c1c4a06ef012e3366d857"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muga"]
    end
  end

  # No zap stanza required
end
